//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentReplacer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentReplacer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlat.
        /// </summary>
        internal static string btnBaslatText {
            get {
                return ResourceManager.GetString("btnBaslatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durdur.
        /// </summary>
        internal static string btnDurdurText {
            get {
                return ResourceManager.GetString("btnDurdurText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EskiDeger.
        /// </summary>
        internal static string cfgEskiDeger {
            get {
                return ResourceManager.GetString("cfgEskiDeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasor.
        /// </summary>
        internal static string cfgKlasor {
            get {
                return ResourceManager.GetString("cfgKlasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzanti.
        /// </summary>
        internal static string cfgUzanti {
            get {
                return ResourceManager.GetString("cfgUzanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YeniDeger.
        /// </summary>
        internal static string cfgYeniDeger {
            get {
                return ResourceManager.GetString("cfgYeniDeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string strBilgiCaption {
            get {
                return ResourceManager.GetString("strBilgiCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uzantısında hiçbir dosya bulunamadı..
        /// </summary>
        internal static string strDosyalarYok {
            get {
                return ResourceManager.GetString("strDosyalarYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksik bilgiler bulunmaktadır..
        /// </summary>
        internal static string strEksikbilgi {
            get {
                return ResourceManager.GetString("strEksikbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dosya güncellendi!.
        /// </summary>
        internal static string strGuncellemeBitti {
            get {
                return ResourceManager.GetString("strGuncellemeBitti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to güncellenirken hata oluştu!.
        /// </summary>
        internal static string strGuncellemeHata {
            get {
                return ResourceManager.GetString("strGuncellemeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dosyası güncelleniyor....
        /// </summary>
        internal static string strGuncelleniyor {
            get {
                return ResourceManager.GetString("strGuncelleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string strHataCaption {
            get {
                return ResourceManager.GetString("strHataCaption", resourceCulture);
            }
        }
    }
}
